name: safee
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  #ENV
  flavor: ^2.0.0
  flutter:
    sdk: flutter

  #UI
  flutter_easyloading: ^3.0.5
  fluttertoast: ^8.2.1

  #API 
  json_annotation: ^4.8.0
  json_serializable: ^6.6.0

  #FIREBASE
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  google_sign_in: ^6.1.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  bloc_concurrency: ^0.2.1
  dartz: ^0.10.1
  shared_preferences: ^2.1.0


dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
